{% set version = '0.2.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-chatgpt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/chatgpt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/chatgpt/chatgpt_{{ version }}.tar.gz
  sha256: ce99d582b104d93571a4a41f2e99496f9a22d302b6b07b96a580f452e3cfe1a8

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-clipr
    - r-httr
    - r-jsonlite
    - r-miniui
    - r-rstudioapi
    - r-shiny
  run:
    - r-base
    - r-clipr
    - r-httr
    - r-jsonlite
    - r-miniui
    - r-rstudioapi
    - r-shiny

test:
  commands:
    - $R -e "library('chatgpt')"           # [not win]
    - "\"%R%\" -e \"library('chatgpt')\""  # [win]

about:
  home: https://github.com/jcrodriguez1989/chatgpt
  license: GPL-3.0-or-later
  summary: '''OpenAI''s ''ChatGPT'' <https://chat.openai.com/> coding assistant for ''RStudio''.
    A set of functions and ''RStudio'' addins that aim to help the R developer in tedious
    coding tasks.'
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: chatgpt
# Type: Package
# Title: Interface to 'ChatGPT' from R
# Version: 0.2.3
# Authors@R: c( person( given = "Juan Cruz", family = "Rodriguez", role = c("aut", "cre"), email = "jcrodriguez@unc.edu.ar" ) )
# Maintainer: Juan Cruz Rodriguez <jcrodriguez@unc.edu.ar>
# Description: 'OpenAI's 'ChatGPT' <https://chat.openai.com/> coding assistant for 'RStudio'. A set of functions and 'RStudio' addins that aim to help the R developer in tedious coding tasks.
# License: GPL (>= 3)
# URL: https://github.com/jcrodriguez1989/chatgpt
# BugReports: https://github.com/jcrodriguez1989/chatgpt/issues
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: clipr, httr, jsonlite, miniUI, rstudioapi, shiny, utils
# NeedsCompilation: no
# Packaged: 2023-05-05 15:07:13 UTC; jcrodriguez
# Author: Juan Cruz Rodriguez [aut, cre]
# Repository: CRAN
# Date/Publication: 2023-05-05 23:00:06 UTC
